[package]
name = "lambda-calculus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.1.3"
chumsky = "0.7.0"
logos = "0.12.0"

[dev-dependencies]
insta = "1.12.0"
